version: '3'
services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql8
    environment:
      MYSQL_DATABASE: 'practice_20211026'
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306

